#!/usr/bin/env python3

import sys
import socket
import signal

UDP_IP = "255.255.255.255"
UDP_PORT = 8888

with open(sys.argv[1], 'wb') as f:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    sock.bind((UDP_IP, UDP_PORT))

    def signal_handler(sig, frame):
        print('STOP')
        f.close()
        sys.exit(0)
    signal.signal(signal.SIGINT, signal_handler)

    while True:
        data, addr = sock.recvfrom(1024)
        f.write(data)